version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: police_training_db
    environment:
      POSTGRES_DB: police_training_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: